### PR TITLE
Add rust demangling tests

### PR DESCRIPTION
**Pull request by l4l**
related to radare/radare2#6426

### CODE REVIEW

**Comment by Maijin** [comment]
Cool stuff, if you could just add an example in a binary that would be enough to cover this functionality :)

**Comment by l4l** [comment]
Here comes a problem: non-stripped rust binaries are kinda big (~3.5mb for helloworld). Do you think it's a good idea

**Comment by Maijin** [comment]
and you can't cheat/mock that somehow ?

**Comment by l4l** [comment]
Hm, I can remove jemalloc & most of unwinding-stuff, but I guess it still take about 0.5-1mb

**Comment by l4l** [comment]
woah, strip magic
now it's ~216k

**Comment by l4l** [comment]
in case someone need of a source:
```rust
#![feature(alloc_system)]
extern crate alloc_system;

struct Foo {
    a: u32,
}

trait Bar {
    fn bar(&self) -> u32;    
}

impl Bar for Foo {
    fn bar(&self) -> u32 {
        self.a
    }
}

fn main() {
    let f = Foo {a : 123};
    f.bar();
}
```

compiled via:
```bash
$ rustc rust.rs -C lto -C panic=abort && strip -g rust
```

**Pull request merged**
