### PR TITLE
x86_32 - assemble xor byte [eax], 0xff

### PR DESCRIPTION
**Pull request by DaniloNC**
Test case for https://github.com/radare/radare2/issues/11249
assemble instruction: xor byte [eax], 0xff -> 8030FF

### CODE REVIEW

**Comment by Maijin** [comment]
Can you use `dB`, if the assembly is not working use `aB` ?

**Comment by DaniloNC** [comment]
My mistake, will fix it.

**Comment by Maijin** [comment]
You can use the github pencil here https://github.com/radare/radare2-regressions/pull/1458/files

**Comment by Maijin** [comment]
Thank you

**Pull request merged**
