### PR TITLE
Added basic SH disassembly test

### PR DESCRIPTION
**Pull request by fenugrec**
For the moment, tests only the "problematic" opcodes (broken; fix coming soon so I didn't mark them as "broken" in the tests)

### CODE REVIEW

**Comment by radare** [comment]
Can you redo this test for the new db?

**Comment by fenugrec** [comment]
Yes, it wasn't clear (and no answer on IRC !) if that was needed. I'll need to install node#$(*&#$ stuff first

**Comment by fenugrec** [comment]
Is there a way to specify endianness in the new db ?

**Comment by Maijin** [comment]
No those need to be done in the new test format, we killed the assembly/disassembly tests already, don't want to add that back

**Comment by fenugrec** [comment]
Sorry, I don't follow. What exactly is deprecated, and where am I supposed to put big-endian disasm tests ?

**Comment by fenugrec** [comment]
Updated to new-style testsuite.

**Pull request merged**
