### PR TITLE
Added sample file + half complete test for cmd_adf

### PR DESCRIPTION
**Pull request by cynecx**
https://github.com/radare/radare2/issues/4007.

Remember this is a half complete test as the actual EXPECT part is missing.

### CODE REVIEW

**Comment by radare** [comment]
waiting for an update

**Comment by cynecx** [comment]
@radare I am not sure if the EXPECT part is correctly formatted as I don't know the absolute correct result.

**Comment by radare** [comment]
@Maijin can you help on this?

**Comment by Maijin** [comment]
If a test is broken, use broken=1.

The offset in the EXPECT looks wrong. The idea of EXPECT is just the reflect of what you would get if it was working :P Having `0x00000006` doesn't look correct take a look at the output of `Cd 100 ; pd 0x10`

**Comment by cynecx** [comment]
@Maijin The problem is that radare's adf command doesn't work with the function (see the test and https://github.com/radare/radare2/issues/4007#issuecomment-202117415), so that I don't know the expected output. But when I apply the adf command to the "wx ..." it works, so I could speculate the output.

**Pull request merged**
