### PR TITLE
Add main tests for arm

### PR DESCRIPTION
**Pull request by daddesio**

### CODE REVIEW

**Comment by daddesio** [comment]
It's my first time creating a r2r test. It looks like the new tests passed for me (BR/XX/FX didn't change):

```
[**] db/formats/elf/helloworld-gcc-elf   OK   48 BR    3 XX    0 FX    0
[OK] db/formats/elf/helloworld-phdr-elf ./helloworld-phdr-elf  29
[**] db/formats/elf/helloworld-phdr-elf   OK   49 BR    3 XX    0 FX    0
[OK] db/formats/elf/ls-alxchk ELF: ls-alchk pie main  38
[**]       db/formats/elf/ls-alxchk   OK   50 BR    3 XX    0 FX    0
[OK] db/formats/elf/m68k ELF: m68k.elf  100
[**]            db/formats/elf/m68k   OK   51 BR    3 XX    0 FX    0
[OK] db/formats/elf/main ELF: main rebased 1  45
[OK] db/formats/elf/main ELF: main rebased 0  47
[OK] db/formats/elf/main ELF: sym.main  28
[OK] db/formats/elf/main ELF: main rebased 2  45
[OK] db/formats/elf/main ELF: main  41
[OK] db/formats/elf/main ELF: main rebased 3  73
[OK] db/formats/elf/main MIPS: main  31
[OK] db/formats/elf/main ELF: pie main  40
[OK] db/formats/elf/main main non common LD script  45
[OK] db/formats/elf/main main wrong sections  39
[OK] db/formats/elf/main main - arm - buildroot-201402  33
[OK] db/formats/elf/main main - arm - linaro-201201  31
[OK] db/formats/elf/main main detection linux64 endbr64  50
[OK] db/formats/elf/main main - arm - linaro-201902  30
[**]            db/formats/elf/main   OK   65 BR    3 XX    0 FX    0
[OK] db/formats/elf/mips ELF: mipsbe-ubusd  30
[OK] db/formats/elf/mips ELF: mipsbe-busybox  34
```

**Comment by radare** [comment]
can you add some more logic in there? this could be also tested with rabin2 -M for example, also do aaa and compare afl and see if the analysis is correct. f.ex

**Comment by daddesio** [comment]
I just copied what the other tests are doing. rabin2 -M works, and afl gives the same output as ?v main. Do you want me to update the tests to run both ?v main and aaa+afl?

**Comment by radare** [comment]
you can do !!!rabin2 -M $R2_FILE in the same test for example

**Comment by radare** [comment]
no need to add more tests, just improve those

**Comment by daddesio** [comment]
OK I only updated the arm tests for now. I used "afo main" instead of afl.

```
[**]            db/formats/elf/main   OK   14 BR    0 XX    0 FX    0
```

**Pull request merged**
