### PR TITLE
added regression test for visual intermediate settings

### PR DESCRIPTION
**Pull request by bluec0re**
Currently broken as I couldn't find a way to press the di d keys.

### CODE REVIEW

**Comment by Maijin** [comment]
@radare this was a question actually ^^

**Comment by radare** [comment]
yep. there's no way to do that. feel free to open an issue in r2 or fix it. the solution would be to create a wrapper function to grab keys

**Comment by Maijin** [comment]
ah ok you seen it ;)

**Comment by radare** [comment]
i know, but the bug is in r2, not in r2r :P you can only pass first order keys to visual mode as arguments :P not everything

**Pull request merged**
