### PR TITLE
add/fix tests to check the mapped flag in sections

### PR DESCRIPTION
**Pull request by ret2libc**
a mapped section will be considered during the virtual2offset
translation and other io related things, while non-mapped sections will
be discarded.

### CODE REVIEW

**Comment by radare** [comment]
Delaying avr support marking them as broken untill all workarounds have been removed?

**Comment by ret2libc** [comment]
yes that's the idea. after https://github.com/radare/radare2-regressions/pull/214 avr will be partially broken but i will fix it soon with the pr on ELF vaddr2paddr and paddr2vaddr

**Comment by radare** [comment]
ok good, just to have it in mind

**Comment by radare** [comment]
Please update for latest master

**Pull request merged**
