### PR TITLE
Fix cmd_search_hit

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by rlaemmert** [comment]
Is there any good reason to change the test in that way instead of just fixing it?
I mean why are you searching for pop instead of the before searched ret?

**Comment by MaskRay** [comment]
pi 4 is incorrect, I suppose it should be pi -4, but backward disassembler is an approximation, and in this case it does not work without function info.

**Comment by Maijin** [comment]
The question was about the following change:

```
-/A ret
 +/A pop
```

**Comment by MaskRay** [comment]
If /A ret was kept, pi -3 would be used. It does not work b/c there is no function info and backward disassembler is imprecise.

**Comment by Maijin** [comment]
What are you talking about ????????????

**Comment by Maijin** [comment]
That's ok then I understand, but why are you fixing BROKEN=1, @radare explicitely said need tofocus on fixing the XX tests...

**Comment by MaskRay** [comment]
Why did you complain when I am fixing this? I was looking at search code and happened to find this issue https://github.com/radare/radare2/pull/8539 so fixed it by the way. What's wrong?

**Comment by Maijin** [comment]
The issue is that you are fixing BR instead of fixing XX...

Already been explained 100000 times that if we don't fix XX we can't control or it's very difficult to know what are the impact of fixed stuff that introduced new XX etc. It's nightmare. So first fix XX then fix BR otherwise we'll get new XX in return to fixed BR which is dumb.

**Pull request merged**
