### PR TITLE
Add t/bug_6678

### PR DESCRIPTION
**Pull request by SchumBlubBlub**
Test for  https://github.com/radare/radare2/issues/6678

### CODE REVIEW

**Comment by Maijin** [comment]
If it's debug -> https://github.com/radare/radare2-regressions/tree/master/t.archos

**Comment by SchumBlubBlub** [comment]
Even if it never steps? this is a crash/no crash on launch.

**Comment by Maijin** [comment]
yes even for that because travis is not able to debug

**Comment by SchumBlubBlub** [comment]
fixed

**Pull request merged**
