### PR TITLE
added test on iaj for imports

### PR DESCRIPTION
**Pull request by wargio**

### CODE REVIEW

**Comment by radare** [comment]
All those seds will make the transition to r2r.js impossible

**Comment by radare** [comment]
Try to kiss

**Comment by wargio** [comment]
i know.. :|

**Comment by Maijin** [comment]
See https://github.com/radare/radare2-regressions/blob/master/t/cmd_json

**Comment by radare** [comment]
wat about just counting the lines of the indented json or something like that? instead of using over nine thousdand sed regexs

**Comment by wargio** [comment]
what about using a command that will be passed to a `match` function in `r2r.js`?

**Pull request closed without merging**
