### PR TITLE
Show a hex diff if binary output differs

### PR DESCRIPTION
**Pull request by jduck**
When a diff contains binary characters, the output is not useful and instead shows only "Binary files differ". Instead, we can use hexdump(1) to do a hexdump diff.

### CODE REVIEW

**Comment by radare** [comment]
Thats a nice idea! Maybe we can use r2 instead of hexdump :p

**Comment by radare** [comment]
use `r2 -nqfcx` instead of `hexdump`

**Comment by jduck** [comment]
It is done!

**Comment by radare** [comment]
it is merged!

**Pull request merged**
