### PR TITLE
Add tests for TLS entry points. (Ref: radare2#4289)

### PR DESCRIPTION
**Pull request by lionaneesh**

### CODE REVIEW

**Comment by radare** [comment]
this is not correct. there's no type= in those entrypoints

**Comment by radare** [comment]
Please update the PR

**Comment by radare** [comment]
anyone's here?

**Comment by lionaneesh** [comment]
Yes. I am at an onsite CTF currently, away from my development machine. I'll get back to you in a day. Sorry for delays!

**Comment by radare** [comment]
ok good to know :) good luck with the ctf!

**Comment by lionaneesh** [comment]
@radare  Updated!

**Comment by radare** [comment]
Cherry-picked, squashed, rebased and commited. Do not git pull *EVER* in a branch. thanks!

**Pull request closed without merging**
