### PR TITLE
Remove x86_olly tests

### PR DESCRIPTION
**Pull request by Svenito**
as it now now lives in r2e

### CODE REVIEW

**Comment by radare** [comment]
X87684654

**Comment by Svenito** [comment]
:question:

**Comment by Maijin** [comment]
Don't remove them, put them in https://github.com/radare/radare2-regressions/tree/master/t.extras + travis rules + makefile change

**Comment by Svenito** [comment]
:+1:

**Comment by Maijin** [comment]
Much better now should be ready for merge 👍

**Pull request merged**
