### PR TITLE
Bug showing wrong offset management with 1 byte enums in big endian mode

### PR DESCRIPTION
**Pull request by elouet**
As per request on issue #8589

### CODE REVIEW

**Comment by Maijin** [comment]
pf tests must be placed in new/db/cmd/cmd_pf

**Comment by elouet** [comment]
Alright, I will update and resubmit.

**Comment by Maijin** [comment]
Just force push on this PR and it will update the PR

**Comment by elouet** [comment]
Please pardon my ignorance, but adding tests to the new/ folder does not seem as straight-forward. I did add the tests but could not figure out a way to run it... Is the new nodejs-based framework further documented somewhere ?

**Comment by Maijin** [comment]
In the README https://github.com/radare/radare2-regressions/tree/master/new#the-newr2r and in the -h of the script

**Comment by radare** [comment]
conflicts

**Comment by radare** [comment]
Conflicts

**Comment by Maijin** [comment]
@radare the issue is not fixed in r2 anyway, I'll merge this week

**Comment by radare** [comment]
cornflakes

**Comment by Maijin** [comment]
Well it's still not merged in r2 https://github.com/radare/radare2/issues/8589

**Comment by radare** [comment]
This is not a pr

**Comment by Maijin** [comment]
I'm quite sure there was also a PR for this but whatever, https://github.com/radare/radare2-regressions/commit/92501239e5dc3985097a390bee0e5163292435cc

**Pull request closed without merging**
