### PR TITLE
regression tests for 3788

### PR DESCRIPTION
**Pull request by ricardoquesada**
regression tests for bug https://github.com/radare/radare2/issues/3788

### CODE REVIEW

**Comment by radare** [comment]
if tests do not pass just mark them as broken to avoid red travis

**Comment by radare** [comment]
i did it for my own

**Comment by ricardoquesada** [comment]
Ah... yes, thanks. I didn't know how to mark a test as broken.

**Comment by radare** [comment]
See my commit after yours in master

**Comment by ricardoquesada** [comment]
thanks.

**Pull request closed without merging**
