### PR TITLE
Add tests for mov flag cmt

### PR DESCRIPTION
**Pull request by kazarmy**
Tests for radare/radare2#7375.

### CODE REVIEW

**Comment by radare** [comment]
uhm, looks worst now to me :?

**Comment by kazarmy** [comment]
Does it look better now?

**Comment by radare** [comment]
yeah

**Comment by radare** [comment]
i dont think this PR fixes the 4 broken tests after your commit in r2

**Comment by radare** [comment]
screen shot 2017-04-28 at 18 25 05

**Comment by kazarmy** [comment]
[run_tests.sh](https://github.com/radare/radare2-regressions/blob/090d439cf165b8b6e35ad6012615ae41d5417af9/run_tests.sh) should really run all tests, instead of just the tests in the `t` dir.

**Pull request merged**
