### PR TITLE
added malloc and -w to these tests

### PR DESCRIPTION
**Pull request by rlaemmert**

### CODE REVIEW

**Comment by Maijin** [comment]
This doesn't seem right, do you really expect user to do r2 -w - ?

**Comment by Maijin** [comment]
A malloc without write permission is pointless

**Comment by radare** [comment]
well, it makes sense if you were able to write on it before making it read-only.. but i agree that we should make debug, malloc and maybe another io desc maps be writable by default

**Comment by Maijin** [comment]
Yes agree on that, being able to change it back to read-only makes sense too.

**Pull request closed without merging**
