### PR TITLE
Fix ?p and ?P

### PR DESCRIPTION
**Pull request by MaskRay**
output changed

### CODE REVIEW

**Comment by Maijin** [comment]
wtf, so you expect ?p and ?P to not display anything ??? This is completly wrong.

**Comment by alvarofe** [comment]
I changed the test didn't know about this change now it shows that section was not found at that dir

**Comment by MaskRay** [comment]
This is not good. Because output format may change, it'd better test the return value.

**Comment by MaskRay** [comment]
I used `2> /dev/null` to not depend on the exact output format.

**Pull request closed without merging**
