### PR TITLE
pr for #2448

### PR DESCRIPTION
**Pull request by VisualPrankDude**
Thanks to Olaf. maybe cd R2_MASTER could be a function.

### CODE REVIEW

**Comment by VisualPrankDude** [comment]
@Maijin update!

**Comment by Maijin** [comment]
I've never use `test` in its pure form but lgtm :+1: 

Still remaining shellcheck are :
* https://github.com/koalaman/shellcheck/wiki/SC2006
And 
* https://github.com/koalaman/shellcheck/wiki/Sc2086 But for this one you have to use array stuff so whatever :p

**Comment by VisualPrankDude** [comment]
use of $() is not the same as ``

**Comment by VisualPrankDude** [comment]
@Maijin about quoting I will do so later, or you develop regex that s/$1/"$1"/ :)

**Comment by Maijin** [comment]
@VisualPrankDude for
a=`git log | grep ^commit | head -n 1 | cut -d ' ' -f2`
a=$(git log | grep ^commit | head -n 1 | cut -d ' ' -f2)

Behave the same here :smiley:

**Comment by VisualPrankDude** [comment]
@montekki last time I checked $(..) ate spaces

**Comment by Maijin** [comment]
ls -m && a=`ls -m` && echo "a=$a" && b=$(ls -m) && echo "b=$b"

    a, b, c
    a=a, b, c
    b=a, b, c

**Comment by VisualPrankDude** [comment]
http://wiki.bash-hackers.org/syntax/expansion/cmdsubst:
so it is about trailing newlines and not spaces. Sory!

 Catch stdout and preserve trailing newlines:

var=$(echo -n $'\n'); echo -n "$var"; # $var == ""
var=$(echo -n $'\n'; echo -n x); var="${var%x}"; echo -n "$var" # $var == "\n"

This adds "x" to the output, which prevents the trailing newlines of the previous commands' output from being deleted by $().

By removing this "x" later on, we are left with the previous commands' output with its trailing newlines.

**Comment by Maijin** [comment]
@VisualPrankDude oh :+1: This should appear on their wiki I think, I'm raising the question on their issue thanks :)

**Comment by Maijin** [comment]
@VisualPrankDude https://github.com/koalaman/shellcheck/issues/364

**Comment by Maijin** [comment]
@VisualPrankDude https://stackoverflow.com/questions/15184358/how-to-avoid-bash-command-substitution-to-remove-the-newline-character?answertab=votes#tab-top Interesting too

**Comment by VisualPrankDude** [comment]
@Maijin ok, thanks. Cool.
can you pull. I will do quoting in separate pr.

**Comment by Maijin** [comment]
Merged ;)

**Pull request closed without merging**
