### PR TITLE
Add another test for ahi s to test radare/radare2#7315

### PR DESCRIPTION
**Pull request by pachulo**
Since radare/radare2@d9d8391 ahi s was not applied when disassembling with pd (but it was when disassembling with pi).

### CODE REVIEW

**Comment by radare** [comment]
This is wrong

You cant use ' inside a single quoted string.

**Comment by pachulo** [comment]
Ups...Sorry about that!

**Comment by kazarmy** [comment]
Superseded by #816. It's basically the same test but somewhat more precise.

**Comment by pachulo** [comment]
I think you can close this one @radare !

**Pull request closed without merging**
