### PR TITLE
Add files generated during tests in .gitignore

### PR DESCRIPTION
**Pull request by giuscri**

### CODE REVIEW

**Comment by Maijin** [comment]
No - 
The file must be deleted for the .newfile
The test must be fixed for def>ghi

**Comment by giuscri** [comment]
OK, changed the PR. I've added some `rm`s at the end of the related test cases. What about that?

**Comment by Maijin** [comment]
arg just realize, why do you use !rm ??? Use rm

**Comment by giuscri** [comment]
OK, fixed in #1177

**Pull request merged**
