### PR TITLE
add testsuite for msvc(functions...)

### PR DESCRIPTION
**Pull request by inisider**
Add tests for function, template demangling

### CODE REVIEW

**Comment by radare** [comment]
thanks!

**Comment by radare** [comment]
you can use iD instead of !rabin2 -D, that will make the tests run faster (avoid forks)

**Comment by radare** [comment]
Can we have a msvc c++ binary in our testsuite, to test that demangling with a real binary? so we can check if the lang is properly detected and so on?

**Comment by inisider** [comment]
Yeap, it is possible, but when i will add the detector.

And all teststuite is also real, i write small application from where than
get all mangled names.

2015-02-19 15:37 GMT+02:00 radare <notifications@github.com>:

> Can we have a msvc c++ binary in our testsuite, to test that demangling
> with a real binary? so we can check if the lang is properly detected and so
> on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2-regressions/pull/143#issuecomment-75052602>
> .
>



-- 
With best regards,
Aleksei

**Comment by XVilka** [comment]
@inisider please also put this application source, to be able to check with various versions of the MSVC (including future ones)

**Comment by inisider** [comment]
I will try to do this when I will back home cause I have different source
at different computers, so need to combine them.


2015-02-19 16:45 GMT+02:00 Anton Kochkov <notifications@github.com>:

> @inisider <https://github.com/inisider> please also put this application
> source, to be able to check with various versions of the MSVC (including
> future ones)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2-regressions/pull/143#issuecomment-75062919>
> .
>



-- 
With best regards,
Aleksei

**Pull request closed without merging**
