### PR TITLE
Tests for Windows

### PR DESCRIPTION
**Pull request by wargio**
Fixed Tests on windows
Added test on signed

### CODE REVIEW

**Comment by wargio** [comment]
@radare this fixes the tests on appveyor

**Comment by radare** [comment]
awesome

**Comment by XVilka** [comment]
@wargio can you please check those too? https://ci.appveyor.com/project/radare/radare2 and https://ci.appveyor.com/project/radare/radare2-hnku1

**Comment by wargio** [comment]
@XVilka https://ci.appveyor.com/project/radare/radare2-hnku1 is missing sys/socket.h
Check if that version of cygwin has it.
The other one fails on building test_list.c (test_list.c:1:20: fatal error: r_list.h missing)
i'll give a look to that.

**Pull request merged**
