### PR TITLE
Update x86

### PR DESCRIPTION
**Pull request by j123123**
more tests

### CODE REVIEW

**Comment by radare** [comment]
all those tests are not passing, so they must be marked as broken....

**Comment by radare** [comment]
that broke travis

**Comment by j123123** [comment]
@radare 
>all those tests are not passing, so they must be marked as broken....

not all. Some of them are not broken.

**Comment by Maijin** [comment]
mark the broken one then :P

**Comment by j123123** [comment]
@Maijin https://github.com/radare/radare2-regressions/pull/452 already done.

**Comment by Maijin** [comment]
👍

**Pull request merged**
