### PR TITLE
Regression tests for afcl, see radare2#13329

### PR DESCRIPTION
**Pull request by fritzr**
Regression tests for [radare2/issues/13329](https://github.com/radare/radare2/issues/13329) "available calling conventions do not properly synchronize with file bitness".

### CODE REVIEW

**Comment by Maijin** [comment]
Can you rebase your PR so it only include your changes?

**Comment by fritzr** [comment]
Done

**Comment by Maijin** [comment]
Thanks @fritzr 

If those tests are currently NOT passing, could you add BROKEN=1 and I will merge

**Comment by Maijin** [comment]
ping @fritzr

**Comment by fritzr** [comment]
Sorry, busy weekend. This is now done.

I also updated the tests -- the original PR would only exhibit the failures on a x64 machine for the `malloc` cases. Now it uses files from `bins` with the right bitness to exhibit the failures.

**Comment by Maijin** [comment]
Perfect thanks!

**Pull request merged**
