### PR TITLE
t/cmd_flags: rename sym flags from bin

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
So.. If this test is passing, which was the problem u was having?

**Comment by ret2libc** [comment]
It's not passing, it's failing.

**Comment by radare** [comment]
Then why it is not marked as broken?

**Comment by ret2libc** [comment]
ret2libc: "ok i'm gonna merge that test after fixing the issue because (hopefully) it should be easy to fix"
pancake: "Ok"

**Comment by radare** [comment]
Dont merge tests that dont pass. 1st rule to keep travis green

**Comment by radare** [comment]
any update on this issue?

**Comment by radare** [comment]
ok to merge now?

**Pull request closed without merging**
