### PR TITLE
t/cmd_search/zignature: add some broken tests

### PR DESCRIPTION
**Pull request by ret2libc**
The most worrying thing is that if you do:
`/x 653b2530000000724b53b834e7150883ec188` on r2r/bins/elf/go_stripped, you have something like:
```
0x0805ae90 hit0_0 653b2530000000724b53b834e7150883ec
0x0805b030 hit0_1 653b2530000000724b53b834e7150883ec
0x0822de2d hit0_2 424f4e445f41445f494e464f5f50415254
0x0822dfcd hit0_3 4c5f4f5645525f4d4143203d203133203b
```
As you can see, the last two hits don't really contain the pattern we were looking for.

### CODE REVIEW

**Comment by radare** [comment]
Maybe related to IO

are those hits in different sections? can you try with search.in=io.section

searching in va mode is a pain

**Comment by ret2libc** [comment]
It works with `search.in=io.section`!

**Comment by radare** [comment]
can you add tests for this search issue?

**Comment by ret2libc** [comment]
It's already here...

**Pull request merged**
