### PR TITLE
[siol fire] Disable p=e tests.

### PR DESCRIPTION
**Pull request by MaskRay**
Both the code and tests are incorrect.
code:

* blocksize is incorrectly calculated (some trailing bytes will be dropped)
* When io.va=1, there are holes in the address space and I think it does
not make much sense to calculate the entropy using the current approach.
* Potential `ut8` overflow of `256 * x`

Test:

* It apparently uses the output from some older version of r2.

The output for the 5 blocks (trailing bytes are dropped) should be:
```
% /tmp/a < bins/elf/arm1.bin
1bec1: 0.764455 256:c3 255:c2
1bec1: 0.757635 256:c1 255:c1
1bec1: 0.778083 256:c7 255:c6
1bec1: 0.642654 256:a4 255:a3
1bec1: 0.634962 256:a2 255:a1
```

### CODE REVIEW

**Comment by XVilka** [comment]
On the other side this command should be tested, so adding a correct test may be a way to go.

**Comment by MaskRay** [comment]
Yes, it should. Or shall I simply mark this test as broken?

**Comment by Maijin** [comment]
if the test are producing wrong output, change the output then mark them as broken.

**Comment by radare** [comment]
what about BROKEN=1 or proper fix instead?

**Comment by MaskRay** [comment]
The file is deleted?

**Comment by Maijin** [comment]
No is not deleted. It's been converted into r2rjs tests

**Pull request closed without merging**
