### PR TITLE
Add test 'mangled elf LOAD0 vaddr fault'

### PR DESCRIPTION
**Pull request by SchumBlubBlub**
(Unfixed) Regression in recent https://github.com/radare/radare2/commit/4fd1e990d9224292bf294c09632acb2f1e67156b

Update: fixed by https://github.com/radare/radare2/pull/6672

### CODE REVIEW

**Comment by Maijin** [comment]
Please put debug tests here https://github.com/radare/radare2-regressions/tree/master/t.archos instead.

**Comment by SchumBlubBlub** [comment]
Done.

**Comment by Maijin** [comment]
Thanks !

**Comment by SchumBlubBlub** [comment]
because is generic problem, got rid of new binary and reused exisiting helloworld instead.

**Comment by SchumBlubBlub** [comment]
Can merge, is green now.

**Pull request merged**
