### PR TITLE
msp430 aFr working in an ELF but not an ihex

### PR DESCRIPTION
**Pull request by BenGardiner**
Adding one test that passes and one that fails to highlight a problem that I've found (and don't know how to fix).

`aFr` (and also `afr`) works to detect `main` in the microcorruption ELF binary already in radare2-regressions. When I try to detect the same function (same bytes) in an ihex along with a .r2 script for flags the result is `aFr` misses the no-return condition at `__stop_progExec__`

### CODE REVIEW

**Comment by radare** [comment]
if the test is not passing mark it as BROKEN

**Comment by BenGardiner** [comment]
my apologies. I've marked the failing test with BROKEN

**Comment by Maijin** [comment]
I see only one test marked as broken, the other one is passing?

**Comment by BenGardiner** [comment]
sorry, I created this PR mostly to try to solve the aFr difference between ELF and ihex. I forgot to open the WIP changes to msp430 disassembly ; see https://github.com/radare/radare2/pull/12447

**Comment by Maijin** [comment]
I've marked both as broken. Feel free to reopen a PR to fix this when fixed.

**Pull request merged**
