### PR TITLE
Add more tests for pf catching bad syntax

### PR DESCRIPTION
**Pull request by SchumBlubBlub**
New regression tests to ensure fix from https://github.com/radare/radare2/pull/6700

### CODE REVIEW

**Comment by radare** [comment]
add also tests for things like `pf 16x 16` -> fieldnames cant be numbers and also a valid `pf 2x x2`

**Comment by SchumBlubBlub** [comment]
added "pf 2x x2".

> fieldnames cant be numbers 

tell that to code:
```
r2 - -qc 'pf 2x 2'  
0x00000000 [0] {
   2 : 0x00000000 = 0x00000000
}
0x00000004 [1] {
   2 : 0x00000004 = 0x00000000
}
```

**Comment by radare** [comment]
yep i know that right now fieldnames can start with a number, but i would remove that possibility to avoid problems in other use cases

**Comment by SchumBlubBlub** [comment]
ok, but different issue, this already better.

**Pull request merged**
