### PR TITLE
Fix tests for rabin2

### PR DESCRIPTION
**Pull request by sivaramaaa**
Hopefully this fixes all tests , expect for 2 related to zignatures (/z) !!!!

### CODE REVIEW

**Comment by radare** [comment]
Agree how to repro

**Comment by Maijin** [comment]
? That's the purpose of the test @radare

**Comment by radare** [comment]
Thats the purpose of me not having to spend time finding the test, decoding b64 and so on

**Comment by Maijin** [comment]
It's not in base64

**Comment by Maijin** [comment]
And I commented the location in github :P

**Comment by sivaramaaa** [comment]
@Maijin I think the output (null) is correct,  because : 
   previous output : ```bind=```
   current output   :  ```(null)```
This is not caused due to some error , it's due to 
```
R_API const char *r_str_get(const char *str) {
        return str? str: nullstr_c;
}
```
```
static const char *nullstr_c = "(null)";
```

**Comment by Maijin** [comment]
ok then go ahead :P

**Pull request merged**
