### PR TITLE
added tests for rahash2 -c parameter

### PR DESCRIPTION
**Pull request by stanciuadrian**
also, corrected zero length md5 test
#150

### CODE REVIEW

**Comment by stanciuadrian** [comment]
Noticed there is no `run_test` after the `printf "admin" | rahash2 -q -a md5 -s -` test. Is this intentional?

**Comment by Maijin** [comment]
probably a mistake please fix :D

**Comment by Maijin** [comment]
@stanciuadrian Don't know if you have seen those issues, but since you're working on rehash2, Maybe you could also help adding some tests for those remaining options #150 ? And/Or fix this issue https://github.com/radare/radare2/issues/3274 ?

**Comment by stanciuadrian** [comment]
Yes, I've seen them. I think I can add some `-B` tests but I have no clue why the SHA-s fail.

**Pull request merged**
