### PR TITLE
Add test cmu_binary_bomb switch case detection

### PR DESCRIPTION
**Pull request by io12**
https://github.com/radare/radare2/pull/10686

### CODE REVIEW

**Comment by Maijin** [comment]
hey @io12 btw did you see https://github.com/radare/radare2/issues/9070 ?

**Comment by io12** [comment]
No, not until now. I'm not sure what the issue is there.

**Comment by Maijin** [comment]
@io12 feel free to ask question in there then ;)

**Comment by ret2libc** [comment]
thanks!

**Comment by Maijin** [comment]
@ret2libc @io12 please see https://github.com/radare/radare2/issues/10966

**Pull request merged**
