### PR TITLE
Added test & bin for pif command invalid instruction issue

### PR DESCRIPTION
**Pull request by hdarwin**
I made tests for https://github.com/radare/radare2/issues/7352.  
if something wrong please let me know to fix it :)  
I tried to make minimized version of test binary but I failed reproduce issue.. so my test is so long..

### CODE REVIEW

**Comment by radare** [comment]
this is expected behaviour. pif shows all instructions inside the function boundaries. you should use pir or pdr

**Comment by hdarwin** [comment]
@radare I wanted to display all instructions inside the function boundaries...  
would please explain more why parsing instructions in function failing is expected??  
when I loaded target binary without base address specific option it works well as expected

**Comment by radare** [comment]
i dont think we want tests that large. if something changes its a pain to maintain and review scrolling up and down. can you find a smaller way to confirm that? maybe using `~?` ?

**Comment by radare** [comment]
i didnt had time to chk your issue yet. maybe someone else from r2land will have some spare time, it's in my queue

**Comment by hdarwin** [comment]
@radare I wanted to reduce the tests size but I couldn't make a small binary which cause same issue.. and the README.md say "Never use shell pipes, use ~" at Advices..

**Comment by Maijin** [comment]
We will probably be able to ban that in r2r.js directly

**Comment by Maijin** [comment]
This has already regress... Why did not you put the ~? as @radare suggested...

**Comment by Maijin** [comment]
Added a working and broken test here https://github.com/radare/radare2-regressions/commit/156d9855074ae2a36167b9f2efcc9193be9ceeaf

**Pull request closed without merging**
