### PR TITLE
Add broken arm thumb s110 sycalls tests

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Some of these probably need to go in other files.
Sadly need a bin for the search one (aae, /c /as) as they utilize $s which isnt available with wx

### CODE REVIEW

**Comment by radare** [comment]
broken? none of those tests are marked as broken

**Comment by jacobrosenthal** [comment]
```
bash-3.2$ r2r db/esil/syscall 
[XX] db/esil/syscall arm s110 syscalls esil  279
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-8365614OJq1HM7Dqx.tmp -
wx 05220aa17cdf
e emu.str=1
pd 3

             0x00000000      0522           movs r2, 5
             0x00000002      0aa1           adr r1, 0x28                ; 0x2c ; ','
-            0x00000004      7cdf           svc 0x7c                    ; '|' ; 124 = sd_ble_gap_device_name_set (0x00000000, 0x00000028, 0x00000005)
+            0x00000004      7cdf           svc 0x7c                    ; '|' ; 0 = sd_ble_gap_device_name_set (0x00000000, 0x00000028, 0x00000005)
EXPECT64=ICAgICAgICAgICAgMHgwMDAwMDAwMCAgICAgIDA1MjIgICAgICAgICAgIG1vdnMgcjIsIDUKICAgICAgICAgICAgMHgwMDAwMDAwMiAgICAgIDBhYTEgICAgICAgICAgIGFkciByMSwgMHgyOCAgICAgICAgICAgICAgICA7IDB4MmMgOyAnLCcKICAgICAgICAgICAgMHgwMDAwMDAwNCAgICAgIDdjZGYgICAgICAgICAgIHN2YyAweDdjICAgICAgICAgICAgICAgICAgICA7ICd8JyA7IDAgPSBzZF9ibGVfZ2FwX2RldmljZV9uYW1lX3NldCAoMHgwMDAwMDAwMCwgMHgwMDAwMDAyOCwgMHgwMDAwMDAwNSkK
[XX] db/esil/syscall arm s110 syscalls as  275
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-836569U3jXf7YoBpd.tmp -
wx 05220aa17cdf
e emu.str=1
s+4
as
pd 1

-124 = sd_ble_gap_device_name_set (0x00000000, 0x00000000, 0x00000000)
-            0x00000004      7cdf           svc 0x7c                    ; '|' ; 124 = sd_ble_gap_device_name_set (0x00000000, 0x00000000, 0x00000000)
+0 = application_0 ()
+            0x00000004      7cdf           svc 0x7c                    ; '|' ; 0 = sd_ble_gap_device_name_set (0x00000000, 0x00000000, 0x00000000)
EXPECT64=MCA9IGFwcGxpY2F0aW9uXzAgKCkKICAgICAgICAgICAgMHgwMDAwMDAwNCAgICAgIDdjZGYgICAgICAgICAgIHN2YyAweDdjICAgICAgICAgICAgICAgICAgICA7ICd8JyA7IDAgPSBzZF9ibGVfZ2FwX2RldmljZV9uYW1lX3NldCAoMHgwMDAwMDAwMCwgMHgwMDAwMDAwMCwgMHgwMDAwMDAwMCkK
[XX] db/esil/syscall arm s110 syscalls as num  315
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656U5WYTYFFijj4.tmp -
wx 05220aa17cdf
e emu.str=1
s+4
as 123
pd 1

-123 = sd_ble_gap_ppcp_get (0x00000000)
-            0x00000004      7cdf           svc 0x7c                    ; '|' ; 124 = sd_ble_gap_device_name_set (0x00000000, 0x00000000, 0x00000000)
+0 = sd_ble_gap_ppcp_get (0x00000000)
+            0x00000004      7cdf           svc 0x7c                    ; '|' ; 0 = sd_ble_gap_device_name_set (0x00000000, 0x00000000, 0x00000000)
EXPECT64=MCA9IHNkX2JsZV9nYXBfcHBjcF9nZXQgKDB4MDAwMDAwMDApCiAgICAgICAgICAgIDB4MDAwMDAwMDQgICAgICA3Y2RmICAgICAgICAgICBzdmMgMHg3YyAgICAgICAgICAgICAgICAgICAgOyAnfCcgOyAwID0gc2RfYmxlX2dhcF9kZXZpY2VfbmFtZV9zZXQgKDB4MDAwMDAwMDAsIDB4MDAwMDAwMDAsIDB4MDAwMDAwMDApCg==
[XX] db/esil/syscall arm s110 syscalls asl ascii  190
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656WNSMYDdhuTc2.tmp -
asl sd_evt_get

-81
+0
EXPECT64=MAo=
[XX] db/esil/syscall arm s110 syscalls asl num  182
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656AmRemV7WRF5O.tmp -
asl 0x51

-sd_evt_get
EXPECT64=
[XX] db/esil/syscall arm s110 syscalls asc num  181
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656g7SFRZMAXm08.tmp -
asc 0x51

-#define SYS_sd_evt_get 81
EXPECT64=
[XX] db/esil/syscall arm s110 syscalls /as  352
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -m 0x16000 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656BXHju3lS63F7.tmp ../bins/elf/BLE_Beacon2.NRF51822_OTA.bin
/as

 0x000168d0 sd_evt_get
 0x000168f2 sd_ble_evt_get
 0x00016b42 sd_ble_gap_sec_params_reply
 0x00016c1c sd_ble_gap_device_name_set
 0x00016c28 sd_ble_gap_appearance_set
 0x00016c32 sd_ble_gap_ppcp_set
 0x00016c3a sd_ble_gap_tx_power_set
 0x00016ce4 sd_ble_gatts_service_add
 0x00016ed6 sd_ble_gatts_sys_attr_set
 0x000171b2 sd_ble_gap_adv_start
 0x00017212 sd_ble_gap_adv_data_set
 0x0001721e sd_ble_gap_appearance_set
 0x00017408 sd_power_pof_threshold_set
-0x000177f6 sd_power_system_off
 0x000177f8 sd_softdevice_disable
 0x00017820 sd_softdevice_vector_table_base_set
 0x0001785c sd_ble_enable
 0x00017864 sd_ble_gap_address_get
 0x0001786c sd_ble_gap_address_set
-0x0001794c sd_ble_gatts_characteristic_add
 0x0001799e sd_ble_gatts_descriptor_add
 0x00017a1a sd_ble_uuid_vs_add
 0x00017d5e sd_softdevice_enable
 0x00017d6a sd_ppi_group_assign
-0x00018660 sd_ble_gatts_value_set
EXPECT64=MHgwMDAxNjhkMCBzZF9ldnRfZ2V0CjB4MDAwMTY4ZjIgc2RfYmxlX2V2dF9nZXQKMHgwMDAxNmI0MiBzZF9ibGVfZ2FwX3NlY19wYXJhbXNfcmVwbHkKMHgwMDAxNmMxYyBzZF9ibGVfZ2FwX2RldmljZV9uYW1lX3NldAoweDAwMDE2YzI4IHNkX2JsZV9nYXBfYXBwZWFyYW5jZV9zZXQKMHgwMDAxNmMzMiBzZF9ibGVfZ2FwX3BwY3Bfc2V0CjB4MDAwMTZjM2Egc2RfYmxlX2dhcF90eF9wb3dlcl9zZXQKMHgwMDAxNmNlNCBzZF9ibGVfZ2F0dHNfc2VydmljZV9hZGQKMHgwMDAxNmVkNiBzZF9ibGVfZ2F0dHNfc3lzX2F0dHJfc2V0CjB4MDAwMTcxYjIgc2RfYmxlX2dhcF9hZHZfc3RhcnQKMHgwMDAxNzIxMiBzZF9ibGVfZ2FwX2Fkdl9kYXRhX3NldAoweDAwMDE3MjFlIHNkX2JsZV9nYXBfYXBwZWFyYW5jZV9zZXQKMHgwMDAxNzQwOCBzZF9wb3dlcl9wb2ZfdGhyZXNob2xkX3NldAoweDAwMDE3N2Y4IHNkX3NvZnRkZXZpY2VfZGlzYWJsZQoweDAwMDE3ODIwIHNkX3NvZnRkZXZpY2VfdmVjdG9yX3RhYmxlX2Jhc2Vfc2V0CjB4MDAwMTc4NWMgc2RfYmxlX2VuYWJsZQoweDAwMDE3ODY0IHNkX2JsZV9nYXBfYWRkcmVzc19nZXQKMHgwMDAxNzg2YyBzZF9ibGVfZ2FwX2FkZHJlc3Nfc2V0CjB4MDAwMTc5OWUgc2RfYmxlX2dhdHRzX2Rlc2NyaXB0b3JfYWRkCjB4MDAwMTdhMWEgc2RfYmxlX3V1aWRfdnNfYWRkCjB4MDAwMTdkNWUgc2Rfc29mdGRldmljZV9lbmFibGUKMHgwMDAxN2Q2YSBzZF9wcGlfZ3JvdXBfYXNzaWduCg==
[XX] db/esil/syscall arm s110 syscalls asca num  150
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-83656hSBNSqhTZuTb.tmp -
asca 0x51

-.equ SYS_sd_evt_get 81
EXPECT64=
[XX] db/esil/syscall arm s110 syscalls aae  383
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -aarm -b16 -easm.os=s110 -m 0x16000 -i /var/folders/hv/syzcx3w10850txk2z6tbnb9m0000gn/T/tmp-836566rekHnPcUtgF.tmp ../bins/elf/BLE_Beacon2.NRF51822_OTA.bin
e bin.baddr = 0x16000;
aae $s @ 0x00016000
fs

 0    0 * sections
 1    0 * segments
 2    0 * relocs
 3    0 * symbols
-4   25 * syscalls
+4   24 * syscalls
 5    5 * strings
EXPECT64=MCAgICAwICogc2VjdGlvbnMKMSAgICAwICogc2VnbWVudHMKMiAgICAwICogcmVsb2NzCjMgICAgMCAqIHN5bWJvbHMKNCAgIDI0ICogc3lzY2FsbHMKNSAgICA1ICogc3RyaW5ncwo=
[**]                db/esil/syscall   OK    8 BR    0 XX    9 FX    0
bash-3.2$ 

```

**Comment by Maijin** [comment]
If the tests are broken, please add the line `BROKEN=1`

**Comment by jacobrosenthal** [comment]
Done

**Comment by Maijin** [comment]
Thank you

**Pull request merged**
