### PR TITLE
Fix tests due to r_bin_elf_p2v_new

### PR DESCRIPTION
**Pull request by kazarmy**
Fixed tests for radare/radare2#11876.

### CODE REVIEW

**Comment by radare** [comment]
wtf are you adding or removing hvaddr?

**Comment by kazarmy** [comment]
Removing hvaddr since if you check with `iSS` (or `readelf`), the first `LOAD` segment doesn't start from 0.

**Comment by radare** [comment]
I know. But system linkers dont always obey this. See mach0 for example. In the debugger you can see the mach0 headers but in r2 not because its wrong

**Comment by kazarmy** [comment]
Whether hvaddr is shown depends on whether there is a mapping from physical address 0x18 to a virtual address. If the headers are loaded anyway (by the debugger) despite what the ELF program header table says, then I suppose you need some linker- or debugger- specific way to find them.

I don't have a mac unfortunately (they're not cheap here) so can't debug mach0 binaries.

**Comment by kazarmy** [comment]
Btw, this show/non-show of hvaddr works only with ELF binaries afaik, not mach0 binaries.

**Comment by radare** [comment]
elf header should be ALWAYS available in memory i dont see a reason to hide the hvaddr

**Comment by radare** [comment]
Same happens on linux

Btw you can setup a macos in vmware or virtualbox with hackintosh. Anyway thats not really important for this issue :)

**Comment by kazarmy** [comment]
> elf header should be ALWAYS available in memory i dont see a reason to hide the hvaddr

Then we are either not living in a flat address space anymore and need segment notation to specify the address, or the elf header needs to be placed in unused memory space.

Wonder which is better....?

**Comment by kazarmy** [comment]
Closed since radare/radare2#11876 was reverted.

**Pull request closed without merging**
