### PR TITLE
Added tests for broken ah- and incorrect ah* output

### PR DESCRIPTION
**Pull request by bluec0re**

### CODE REVIEW

**Comment by Maijin** [comment]
Tests for that ?

**Comment by Maijin** [comment]
Wtf is https://github.com/radare/radare2-regressions/pull/581/files#diff-49cf3d246137fff0402fcfc5275a8182R18 "immbase:" When testing you're supposed to predict output, those won't be printed same for this XXXX - XXXX

**Comment by bluec0re** [comment]
sry, don't get what you mean by this comment. Here you'll find the output as an asciicast:
https://asciinema.org/a/6mic40z60p4bkaza0c83lqbud

The tests are btw generated based on the source code + help texts here:
https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3563

**Comment by Maijin** [comment]
Ok my bad ;)

**Comment by Maijin** [comment]
DIdn't see ah

**Pull request merged**
