### PR TITLE
add a test for invalid 64 bit instruction

### PR DESCRIPTION
**Pull request by mrexodia**
mov ah, byte ptr [r8]

radare/radare2#8097

### CODE REVIEW

**Comment by radare** [comment]
not gonna merge if the tests is not passing

mark it as broken or fix x86.nz <http://x86.nz/> to handle that properly

**Comment by mrexodia** [comment]
Donnow, @Maijin asked me to create a pull request for the test. I don't quite know how to mark it as broken...

**Comment by Maijin** [comment]
well it's written "br"

**Comment by Maijin** [comment]
just add that in your commit @mrexodia

**Comment by radare** [comment]
conflict.
 also

```
prop:core pancake$ rasm2 -a x86 -b 64 "mov ah, byte ptr [r8]"
678a28
prop:core pancake$ rasm2 -a x86 -b 64 -d 678a28
mov ch, byte [eax]
```

**Comment by mrexodia** [comment]
> rasm2 -a x86 -b 64 "mov ah, byte ptr [r8]"

This should not yield any result since it's an invalid instruction, but I don't know how to say that in the test...

**Comment by Maijin** [comment]
image
like
image

**Comment by mrexodia** [comment]
like this? it makes no sense to me that there are bytes between the instruction and `"br"` but whatever

**Comment by radare** [comment]
the byets represent the correct output, and that BR marks that it should ignore the error, in case the thing is fixed the testsuite will show FIXED, if it was not marked as broken then it will show OK or ERROR.

so it makes sense

**Comment by mrexodia** [comment]
Oki 👍

It was just rather unclear to me because of this line:

`test_invalid "${PLUGIN}" "mov byte [rbp-0x100], 2" c68500ffffff02`

And also:

`test_invalid "${PLUGIN}" "mov byte [eax], 0" c60000`

**Pull request closed without merging**
