### PR TITLE
index.js: support multiline CMDS and EXPECT

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by Maijin** [comment]
What, you can already do multiline, just use CMD64 or use r2r.js command that add test

**Comment by radare** [comment]
its easier to write non-base64, so lgtm

**Comment by Maijin** [comment]
but dangerous... then we get back to the original point of having trailingspaces etc.

**Comment by Maijin** [comment]
And it won't have auto-fix capability etc.

**Comment by kazarmy** [comment]
> but dangerous... then we get back to the original point of having trailingspaces etc.

Trailing spaces can be trimmed.

> And it won't have auto-fix capability etc.

What auto-fix capability?

**Comment by radare** [comment]
r2r.js -i

**Comment by radare** [comment]
agree, but we already have CMDS, so handling multiline is not that heavy

**Comment by Maijin** [comment]
The base64 tests can automatically be fixed when they are XX so we don't have to change them manually and for the trailingspace they can be trimmed always but that's super annoying

**Comment by Maijin** [comment]
To add a new test just use  -a    add new test

**Comment by kazarmy** [comment]
> r2r.js -i

Oh you mean `r2r -R` which calls `new/bin/r2r.js -i`.

> The base64 tests can automatically be fixed when they are XX so we don't have to change them manually

Adding CMDS and EXPECT auto-fix support to r2r.js similar to the support for CMDS64 and EXPECT64 seems doable.

> and for the trailingspace they can be trimmed always but that's super annoying

This can be done automatically using the `trim()` method.

**Comment by Maijin** [comment]
trim() is for after the test has been created and also that's one of the many encoding issues encountered in current r2r, imho we should have just CMD64 and EXPECT64 especially since the end-goal is to make an interface, having to manage multiple way of encoding doesn't make sense and gonna double the amount of work for maintenance

**Comment by Maijin** [comment]
Instead of this, we should make a proper `r2r -a` that takes commands as input and generate CMD64 and EXPECT64

**Comment by kazarmy** [comment]
> trim() is for after the test has been created

Each line of the test can be trimmed.

> we should have just CMD64 and EXPECT64

Diffs involving CMD64 and EXPECT64 can't be read easily.

**Comment by Maijin** [comment]
Diffs involving CMD64 and EXPECT64 can't be read easily. ??? But you never have to do diff for that you use the r2r toolings which does that for you.

Each line of the test can be trimmed. that's not the issue, the issue is that r2 commands still have tons of trailingspace, everytime you save a test with trailingspace in it it's huge pain

**Comment by kazarmy** [comment]
> But you never have to do diff for that you use the r2r toolings which does that for you.

They can't be read easily on GitHub.

>  r2 commands still have tons of trailingspace

I don't get this. Need an example.

**Comment by Maijin** [comment]
Can't be read easily on Github but don't have to be either, in fine i'll just have to convert your test in base64 once it's merged so it's consistent with the rest :( 

I don't get this. Need an example -> git log | grep trail

**Comment by Maijin** [comment]
The ultimate goal is to have an interface potentially web-based for the tests to be modified/visualised/perform statistics on them to know which commands are tested etc.

**Comment by Maijin** [comment]
Can you remove the trim logic ? I can't merge the PR at all with the trimming otherwise if the output radare2 has trailspace it will fail

**Comment by kazarmy** [comment]
> Can you remove the trim logic ?

Ok done. I've added a test showing this. I've even highlighted trailing space in the correct EXPECT statement as follows:
test_with_trailing_space

I hope you like it.

**Comment by kazarmy** [comment]
> The ultimate goal is to have an interface potentially web-based for the tests to be modified/visualised/perform statistics on them to know which commands are tested etc.

:thumbsup:

> fine i'll just have to convert your test in base64 once it's merged so it's consistent with the rest :(

I'll do this myself, no worries. It's just that the cmd_i test is incomplete and I don't want to leave it in `t` because it would then require the old test infrastructure.

**Comment by kazarmy** [comment]
There's repeated code in 3b06c13dbb54337a87bd878223d334d0ef950553 that can be refactored later. Also, I know that the delimiter used can be incompatible with the content, but only in rare cases and an automatic delimiter chooser can be done later.

**Pull request merged**
