### PR TITLE
Fix cmd_project:asm.emu in project: 0x0 is no longer mapped implicitl…

### PR DESCRIPTION
**Pull request by MaskRay**
…y when io.va=1

### CODE REVIEW

**Comment by Maijin** [comment]
Change the tests commands then to e io.va=true

**Comment by MaskRay** [comment]
Changed

**Comment by Maijin** [comment]
wouldn't this "om `o~[0]` 0" worth to be a dedicated command/alias ?

**Comment by Maijin** [comment]
Also this ```om `o~[0]` 0``` needs to be done before the project is saved.

**Comment by Maijin** [comment]
an alias like like:

`| Sf [baddr]                    Alias for S 0 0 $s $s foo mrwx`

Maybe ?

**Comment by Maijin** [comment]
@radare to review

**Comment by radare** [comment]
the test is not really a good one, but yeah this fixes the behaviour

**Comment by Maijin** [comment]
Yes it's bad because it implies the user to know about using this ```om `o~[0]` 0``` which I hardly doubt any will.

**Comment by radare** [comment]
omm does that, doing that o~[0] is wrong and hacky, but yep its a bad test, mainly because pa shouldnt be mapped in va mode, but this is an issue with the test, not with r2

**Pull request merged**
