### PR TITLE
[t.esil] arm-16: add test for LDR (register) (#6387)

### PR DESCRIPTION
**Pull request by ekiwi**
This documents a possible bug reported in [issue #6387](https://github.com/radare/radare2/issues/6387).

### CODE REVIEW

**Comment by radare** [comment]
conflicts

**Comment by radare** [comment]
put them all in a single pr

**Comment by mrmacete** [comment]
awesome!

btw, i think in general on ESIL tests it's better to test the emulation results instead of the esil expression itself, like this:

```
NAME="ldr r2, [r3, r1]"
BROKEN=true
FILE=malloc://0x200
CMDS='
e asm.arch=arm
e asm.bits=16
ar r3=1
ar r1=2
wx 5a58aabbccddeeff
aes
ar r2
'
EXPECT='0xeeddccbb
'
run_test
```

I'm fixing this, and for example my ESIL expression for implementing that is `0xffffffff,r1,r3,+,&,[4],r2,=` which is a nitpick, but it's more correct by limiting the address space to 32 bits. Value-driven tests are robust to this kind of nits ;)

**Comment by ekiwi** [comment]
> btw, i think in general on ESIL tests it's better to test the emulation results instead of the esil expression itself

Yes. Makes the test a lot more robust in respect to refactoring the code.

> I'm fixing this, and for example my ESIL expression for implementing that is 0xffffffff,r1,r3,+,&,[4],r2,=

Cool. I was investigating the issue a bit more and it seems the problem is here: https://github.com/radare/radare2/blob/f2ba8ca3f5387e2c90387097504c40edd384c7be/libr/anal/p/anal_arm_cs.c#L892

Where it is incorrectly assumed that the instruction will always use a constant offset instead of a register value. The name of the register (in the test above `r1`) can be retrieved like this:

~~~{.c}
#define MEMINDEX(x) r_str_get (cs_reg_name(*handle, insn->detail->arm.operands[x].mem.index))
~~~

I just haven't figured out how to tell when to use the `disp` and when to use the `index` register.


> my ESIL expression for implementing that is 0xffffffff,r1,r3,+,&,[4],r2,= which is a nitpick, but it's more correct by limiting the address space to 32 bits

Doesn't that just "reinforce" the overflow behavior that is already implied in the semantics of the `+` command? (since this is a 32bit architecture)

**Comment by mrmacete** [comment]
well, at the moment the `+` command doesn't enforce the width by itself: https://github.com/radare/radare2/blob/f2ba8ca3f5387e2c90387097504c40edd384c7be/libr/anal/esil.c#L1356

```
$ r2 -a arm -b 16 -
[0x00000000]> ar r1=0xffffffff
[0x00000000]> ar r2=0x00000001
[0x00000000]> "ae r1,r2,+"
0x100000000
```

**Comment by mrmacete** [comment]
the solution i'm proposing is borrowing from the arm64 case, by extending the `else` case and defining the macro:
```
#define HASMEMINDEX(x) insn->detail->arm.operands[x].mem.index != ARM_REG_INVALID
```
and testing that (just like in arm64)

**Comment by ekiwi** [comment]
> the solution i'm proposing is borrowing from the arm64 case, by extending the else case and defining the macro:

ok. should I implement that and submit a pull request?

**Comment by mrmacete** [comment]
sure, if you are in the mood! :smile:

**Comment by ekiwi** [comment]
I changed the test to check the results of the instruction instead of the ESIL string as suggested by @mrmacete.

**Comment by radare** [comment]
your pr in r2 breaks 2 tests. can you update them in this pr?

**Comment by ekiwi** [comment]
@radare I fixed the two tests that were checking for incorrect ESIL commands. Should I mark them as `BROKEN`, as they reveal a bug in the current `master` branch of `r2`?

**Comment by radare** [comment]
mark them as broken or fix them in r2. let me know and i’ll merge.

**Comment by ekiwi** [comment]
> mark them as broken or fix them in r2. let me know and i’ll merge.

they are fixed in my pull request: https://github.com/radare/radare2/pull/6422
Just not in the current master of `r2`

**Comment by Maijin** [comment]
If you fixed them in your PR then don't broken them and pancake will just have to merge both PR

**Comment by ekiwi** [comment]
> If you fixed them in your PR then don't broken them and pancake will just have to merge both PR

Yes. I was over thinking the circular dependency that we have here ;-)

(If this pull request is merged first, CI will fail on `radare2/master`. If the fix in `r2` is merged first, then it won't have passed all tests, as currently there are two wrong tests on `radare2-regressions/master`.)

**Pull request merged**
