### PR TITLE
Trace test for #5473

### PR DESCRIPTION
**Pull request by monosource**
This PR adds a test to help with the following issue: https://github.com/radare/radare2/issues/5473

### CODE REVIEW

**Comment by Maijin** [comment]
```
#!/bin/sh
# GPL 3+ - Copyright (C) 2016  pancake, jduck
```

To be changed and  

```
# "!" - run commands (via system)
```

to be removed.

**Comment by monosource** [comment]
Updated.

**Comment by Maijin** [comment]
I still see ` pancake, jduck`

**Comment by monosource** [comment]
Updated.

**Comment by radare** [comment]
thanks

**Pull request merged**
