### PR TITLE
Fix tests for PR radare/radare2#4846

### PR DESCRIPTION
**Pull request by Svenito**
Insert space after the wx command.  

radare/radare2#4846

### CODE REVIEW

**Comment by Maijin** [comment]
? you realised that your fix broke 125 tests :P

**Comment by Maijin** [comment]
You have to fix them too !

**Comment by Svenito** [comment]
Devastating. I'll get on the fixes.

**Comment by Maijin** [comment]
I didn't check wether is r2r and r2 fix, but whatever 👍

**Comment by radare** [comment]
Can you add a test for `wxf`  too?

**Comment by Svenito** [comment]
Yep, would you prefer a new PR, or shall I add it to this one?

**Comment by radare** [comment]
A new one, this is closed now. i m fixing the testsuite, dont worry about the redness

**Pull request merged**
