### PR TITLE
Delete `wt map`

### PR DESCRIPTION
**Pull request by MaskRay**
It does not make sense after siol.

### CODE REVIEW

**Comment by Maijin** [comment]
What's the alternative now ?

**Comment by MaskRay** [comment]
This is an empty file and there is no mappings (`om`), `wx` should not resize the file.

**Comment by Maijin** [comment]
good for me since it's using ls it must go away anyhow

**Comment by Maijin** [comment]
can you resolve conflict ?

**Comment by MaskRay** [comment]
Rebased.

**Pull request merged**
