### PR TITLE
r2r: Don't always exit gracefully

### PR DESCRIPTION
**Pull request by AlexKornitzer**
As pancake pointed out, always exiting on 0 will stop us exiting with an error when the tests error. Thus, lets use a fail flag that we mark anytime a test fails.

Are you okay with it always exiting with 1 for an error?

### CODE REVIEW

**Comment by AlexKornitzer** [comment]
@radare @XVilka, can we merge this in? I will rebase if that is no required, this is needed to stop some tests fake passing in travis, etc.

**Comment by Maijin** [comment]
Merging

**Comment by Maijin** [comment]
If it doesn't work we can always revert

**Comment by AlexKornitzer** [comment]
^ True :)

**Comment by Maijin** [comment]
works.

**Pull request merged**
