### PR TITLE
fix for radare2-PR-#8629 ?l

### PR DESCRIPTION
**Pull request by firmianay**
fix ?l and ?d #8629

?l command doesn't print result before.

### CODE REVIEW

**Comment by radare** [comment]
the problem here is that ?l and ?d was suposed to just modify the $? variable and not trash the output.. so that breaks a bit the original logic.. maybe we can use/add a command operator to put the output of the command into value..someting like `?l foo~$`. this way we can just apply your patch and not trash the output to set the num->value and have the ability to set the $? var from any command

**Comment by kazarmy** [comment]
lgtm ... `?$` already taken.

**Comment by radare** [comment]
nope i said ~$

**Comment by kazarmy** [comment]
I meant something like `?$l foo`, but `?l foo~$` looks good to me.

**Pull request closed without merging**
