### PR TITLE
Add m68k symbolic label test on Genesis ROM.

### PR DESCRIPTION
**Pull request by cr1901**
This pull request is not ready, but I am unsure how to proceed. The test itself should be fine, but whenever I run the test suite, r2 can't seem to find the file I'm trying to open even though it's inside the radare2-regressions repository!

Doing a `grep` for `file.path` inside the repo suggests that my syntax is correct (to do a relative path lookup for the file). Any idea what might possibly be causing this output?

Command invoked was: `PATH=../../../radare2/radare2-w32-0.10.5-git/:$PATH ./m68k`

```
[XX]  8  m68k: : m68k symbolic labels

Regression: ./m68k
Command:  /home/William/src/radare2/radare2-w32-0.10.5-git/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//m68k-ZXkhTs/rad   - > /tmp/r2-regressions//m68k-ZXkhTs/out 2> /tmp/r2-regressions//m68k-ZXkhTs/err
File: -
Script: e asm.arch=m68k
e file.path=../../bins/smd/LiquidSpaceDodgerV3.bin
s 0x21a
f sym.z80BusReq @ 0x00a11100
pi 1

Diff: --- /tmp/r2-regressions//m68k-ZXkhTs/exp  2016-08-09 15:32:56.697343200 -0400
+++ /tmp/r2-regressions//m68k-ZXkhTs/out        2016-08-09 15:32:56.777347800 -0400
@@ -1 +1 @@
-move.w section.header, sym.z80BusReq
+linef
```

The last line should be: `move.w section.header, 0xa11100.l`, since the label bug still exists.

### CODE REVIEW

**Comment by Maijin** [comment]
If you would have looked at other tests you would see that you need to use FILE=XXX

**Comment by Maijin** [comment]
It's also documented in the README.md at the root

**Comment by cr1901** [comment]
Sorry. Fixed now. Should be ready to go.

**Comment by Maijin** [comment]
Is the test currently passing ? If no, set BROKEN=1

**Comment by cr1901** [comment]
A number of tests are currently not passing. Okay to set all tests which don't work to BROKEN=1 in the file? Asking just in case.

**Comment by Maijin** [comment]
If they don't pass they have to be put in BROKEN=1. But they already pass otherwise the CI would be RED

**Comment by cr1901** [comment]
@Maijin Please see this screenshot of my tests:
image

Tests 1, 3, and 8 (m68k file) do not pass, but none of the tests have `BROKEN` set to 1.

**Comment by Maijin** [comment]
Good, that means the bug is windows only because they pass on linux.

**Comment by radare** [comment]
if the test is not passing mark it as BROKEN=1

**Comment by Maijin** [comment]
So just mark yours as broken.

**Comment by Maijin** [comment]
@skuater can you check the existing tests mentionned to be failing on windows?

**Comment by radare** [comment]
merged and fixed the issue.

the problem is because it cant replace two numbers in a single instruction. but in fact the first value was replaced for section.... which is wrong because 0x100 is the value that should be set. I have just ignored the section. flags which are probably not useful in the disasm, but the ideal solution would be to fix parse/parse.c to continue instead of return true when parsing the string

**Comment by radare** [comment]
let me know if you find any other case where this fails

**Comment by cr1901** [comment]
This bug was probably unrelated to [Issue #4304](https://github.com/radare/radare2/issues/4304), but nevertheless it's good this bug was fixed.

Won't have time till at least Friday to test this though.

**Pull request closed without merging**
